### ISSUE TITLE
Home assistant complaints about MQTT entity names

### ISSUE THREAD

**Issue by lemppari** [mKeRix/room-assistant#1475]
With a new version of Home assistant 2023.8 there is a  repair suggestion for entities from room-assistant MQTT integration: "Discovered entities with a name that starts with the device name". This stops working in version 2024.2.0. Please address before upgrading.

I guess this must be fixed from room-assistant.

**Comment by shizmebob** [comment]
Hey @lemppari - I see this also. Given there has been no work done on this project for a while I took a look at the source code. I only use the xiaomi-mi integration and I think I just need to change one line to correct this. I will do this locally in my stack but if that will fix your usecase as well I can go to the trouble of a fork in github? Not going to bother if it wont help anyone.

**Comment by lemppari** [comment]
@shizmebob, if your change fixes the problem, please release it. At least tell what to change and where. I will then have to try to find out how I can get my installations updated...

**Comment by mushuthecat** [comment]
Hello,

Same issue on my side im using room assistant for presence detection and i also get this warning ?

Any release soon ?

![image](https://github.com/mKeRix/room-assistant/assets/83928911/0747def5-0f04-4f93-88d8-9a2db8e61b58)

**Comment by shizmebob** [comment]
@lemppari / @mushuthecat my attempt at a fix worked for me. Its available at https://github.com/shizmebob/room-assistant

Pull request made: https://github.com/mKeRix/room-assistant/pull/1477

You can hack the change in locally pretty easily if you need to as well as its just deleting a few characters. After that I had to wait for my devices to send new information through then restart HA and my warnings cleared. Hopefully one of the maintainers will accept the simple change and publish.

**Comment by lemppari** [comment]
@shizmebob @mushuthecat I made that fix locally, but still I get errors in Homeassistant log. Maybe the fix is only for xiaomi-mi integration. I can't find where the entity name is created for MQTT integration.

**Comment by shizmebob** [comment]
@lemppari - I cant see anything obvious either. What hardware do you use with room-assistant?

**Comment by lemppari** [comment]
@shizmebob All my room-assistants are running on Raspberry Pi Zero W and talking to homeassistant through mqtt.

**Comment by mushuthecat** [comment]
Hi,

My Room-Assistant are running on docker container and everithing works perfectly im using them for room detection using BLE on my android devices.

I do not realy understand what we have to do to workaround this issue before the 2024 update...

Regards

**Comment by lemppari** [comment]
It looks like I managed to fix my environment. I am running Raspberry Pis for room-assistants and they talk to Homeassistant via MQTT. I am using  Bluetooth-classic integration for monitoring. I don't know how the deployment path goes from Github to npm for my devices, so I just updated the latest version of room-assistant to my clients and modified the code there. I dealed with the .js files on my devices, but here are the changes in the Github .ts versions.

For all the following lines I removed the ${baseName} and ${instanceName} (and following space) from the strings. The .ts files will be converted to .js files in the clients, so they look different but are obviously easily spotted there too.

src/integrations/bluetooth-classic/bluetooth-classic.service.ts
369:      `${baseName} Room Presence`,

src/integrations/bluetooth-classic/bluetooth-classic.service.ts
354:      `${baseName} Tracker`,

src/integrations/bluetooth-classic/bluetooth-classic.service.ts
317:        `${instanceName} Bluetooth Inquiries`

src/status/status.service.ts
97:      new Sensor('status-cluster-leader', `${instanceName} Cluster Leader`),

src/status/status.service.ts
74:      new Sensor('status-cluster-size', `${instanceName} Cluster Size`),

**Comment by shizmebob** [comment]
hey @lemppari - do you want me to give you access to my fork and you can add these fixes there?

**Comment by lemppari** [comment]
@shizmebob Thanks, sure I can do that.

**Comment by shizmebob** [comment]
@lemppari - you should have an invite now

**Comment by lemppari** [comment]
@shizmebob Thanks! I made changes to your fork. As I mentioned those changes fixed my installation, hopefully there are no unwanted side effects.

I had to remove some retain messages from my Homeassistant MQTT broker manually. I tried various methods for fixing before I found the correct places. Used MQTT Explorer for that.

**Comment by Duke-Box** [comment]
Hi,

I get the same warnings. I run room assistant on a pi zero w using classic bluetooth to detect my phones.
I have read this thread but don't understand what I need to do to correct this.

It seems that a local edit of the 'json files is all that is required
Where are the files that need editing on my pi zero located? 
If you could point me there I could edit directly.

Or how do I use the fork on Github to upgrade my room-assistant installation?
A step by step instruction would be appreciated, but I would prefer to edit the files locally as I only have one room assistant instance.

Many thanks in advance.

**Comment by mushuthecat** [comment]
Hi,

Same request for me can we have a step by step instructions ?

Regards

**Comment by Duke-Box** [comment]
@shizmebob @lemppari

Ok I have tried to edit the local files but I cannot find them.

Please can you tell me where the "local" files are so I can edit them. You both say these files can be hacked locally on the device that is running Room Assistant, but where are they? What directory are they in?
I have run a find / *.js and come up with hundreds of files.
I have run a grep -l "$baseName Room Presence" and had no luck as it is taking forever.

ANY help would be appreciated.

**Comment by lemppari** [comment]
@Duke-Box , local files are in the directories under /opt/nodejs/lib/node_modules/room-assistant/dist/:
/opt/nodejs/lib/node_modules/room-assistant/dist/integrations/bluetooth-classic/bluetooth-classic.service.js
/opt/nodejs/lib/node_modules/room-assistant/dist/status/status.service.js

**Comment by Duke-Box** [comment]
@lemppari 
Thanks for the file locations.
I have edited the files as per your above post.

Your information is Very much appreciated!

**Comment by lemppari** [comment]
And actually Home Assistant doesn't complain any more. See https://github.com/home-assistant/core/pull/98768 But maybe this could still remain open just in case room-assistant folks wake up.

**Comment by Duke-Box** [comment]
I'm on 2023.8.4 and HA still complains in my case. I wonder if it didn't
make the release?

Edit: just reverted all the .js files back to the originals, restarted room assistant and reload MQTT on HA.
Still warnings in the logs., which had gone after editing the .js files as per above.

So in my case Frencks PR either didn't make it to the release or it isn't fixed!

Edit EDIT:
So looking in more detail, Frenck is discussing a Repair issue not a log warning, so I guess this isn't fixed at all.

**Comment by Scott8586** [comment]
I tend to use room-assistant in a combination of natively on pi zeros, but also in docker containers on pi 3B+s.  Will there be a way to get these changes incorporated into a public docker image?

**Comment by austwhite** [comment]
The issue is still present as far as naming, but Home Assistant stopped showing it as a repair iten.   
Still have until release 2024.2 to fix this, but I have noticed Room Assistant development has slowed right down.   I hope the developers are still maintaining it.....
There are a lot less BLE room presense options around now.   I guess mm wave technology is slowly replacing them.

**Comment by TheQue42** [comment]
Since this component, unfortunately seems to be dead, it still an issue.

**Comment by austwhite** [comment]
Unfortunately this is the issue with custom components.  They are only as good as the maintenance of the component.  Once the maintainer steps back they are slow to be updated

**Comment by lemppari** [comment]
Room assistant seems to be dead project...
